ndbc-taxonomy-icon-webjar
=========================

Whats's this?
-------------

This is a tiny script to re-package
http://dbarchive.biosciencedbc.jp/en/taxonomy-icon/desc.html[Taxonomy Icons from NBDC]
as http://www.webjars.org/[WebJars].


Usage
-----

. Download `taxonomy_icon_en.zip` and `taxonomy_icon_png.zip` from
  http://dbarchive.biosciencedbc.jp/en/taxonomy-icon/download.html,
  and decompress them

. run `generate-webjar.py` like below:

    $ python generate-webjar.py /path/to/taxonomy_icon.csv /path/to/taxonomy_icon_png/directory /path/to/jar/to/be/generated


Generated JAR file contains PNG files and a JSON file.
PNG files are just copied from original icon files, but renamed like
`[taxonomy id]-[size and background].png`.
The JSON file contains list of species (taxonomy IDs) included in the JAR file.


License
-------

`generate-webjar.py` is licensed under
https://creativecommons.org/publicdomain/zero/1.0/deed.en[CC0].

This repository contains `nbdc-taxonomy-icon-20130321.jar` generated by the script.
The original http://dbarchive.biosciencedbc.jp/en/taxonomy-icon/desc.html[Taxonomy Icon]
is created by http://biosciencedbc.jp/en/[Database Center for Life Science] and licensed under
http://creativecommons.org/licenses/by/2.1/jp/deed.en[Creative Commons Attribution 2.1 Japan].
License of the JAR file also follows the original license.
